# Generated by Django 5.0.4 on 2024-05-29 06:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=30)),
                ('form_number', models.IntegerField(default=0)),
                ('Plan_forthe_Next_Month', models.CharField(default='0', max_length=255)),
                ('remarks', models.TextField(blank=True, default='0')),
                ('attachment', models.FileField(null=True, upload_to='attachments/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field_Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=50)),
                ('form_number', models.IntegerField(default=0)),
                ('title_creation', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('edit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Mas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationname', models.CharField(max_length=255)),
                ('divisionname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=50)),
                ('divisions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserMas',
            fields=[
                ('s_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('approval_request_raised_by', models.CharField(max_length=255)),
                ('request_status', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable', models.BooleanField(default=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_dash.show')),
            ],
        ),
        migrations.CreateModel(
            name='Title_Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_creation', models.CharField(blank=True, max_length=255)),
                ('field_name', models.ManyToManyField(to='mis_dash.field_creation')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='list',
            field=models.ManyToManyField(through='mis_dash.Disable', to='mis_dash.title_creation'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('Division', models.CharField(max_length=200)),
                ('Title_Creation_names', models.ManyToManyField(to='mis_dash.title_creation')),
            ],
        ),
        migrations.AddField(
            model_name='disable',
            name='title_creation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_dash.title_creation'),
        ),
    ]
