# Generated by Django 5.0.4 on 2024-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='remarks',
            field=models.CharField(max_length=30),
        ),
    ]
